# Generated by Django 5.2.1 on 2025-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_procedimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
