# Generated by Django 5.2.1 on 2025-05-28 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_agendamento_user_alter_paciente_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
